kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: fast
provisioner: kubernetes.io/storageos
parameters:
  apiAddress: tcp://localhost:8000
  apiUser: storageos
  apiPassword: storageos
