apiVersion: v1
kind: Service
metadata:
  name: storageos-controller
  labels:
    app: storageos-controller
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  selector:
    app: storageos-controller
