apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: storageos-controller
  labels:
    tier: storage
    app: storageos-controller
    version: v1
spec:
  template:
    metadata:
      labels:
        name: storageos
    spec:
      # Filter to specific nodes:
      # nodeSelector:
      #  app: storageos
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
        # - name: test
        #   image: quay.io/storageos/storageos:simon
        #   imagePullPolicy: Always
        #   command: [ "/usr/bin/env" ]
        - name: controlplane
          image: quay.io/storageos/storageos:simon
          # image: storageos:latest
          imagePullPolicy: Always
          command: [ "/bin/storageos", "server" ]
          securityContext:
            privileged: true
          volumeMounts:
            - name: storageos-state
              mountPath: /storageos
          ports:
            - containerPort: 8000
              protocol: TCP
      volumes:
        - name: storageos-state
          hostPath:
              path: /storageos
      imagePullSecrets:
        - name: quay
