apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - name: http
    port: 8083
  - name: api
    port: 8086
  - name: colectd-udp
    protocol: "UDP"
    port: 25826
  selector:
    app: influxdb
