apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: influxdb
spec:
  serviceName: influxdb
  replicas: 1
  template:
    metadata:
      name: influxdb
      labels:
        app: influxdb
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: influxdb
        image: "quay.io/storageos/influxdb:beta"
        ports:
        - name: http
          containerPort: 8083
        - name: api
          containerPort: 8086
        - name: collectd-udp
          protocol: "UDP"
          containerPort: 25826
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/influxdb
      imagePullSecrets:
        - name: quay
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
        volume.alpha.kubernetes.io/storage-class: HostPath
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 100Mi
